aws:
  region: us-west-2
  s3Bucket: dt-eventsstore-prd
  s3Folder: dt_storesalesservice_canonical_appointment_v2_avro_prd
athena:
  database: ore_recon
  tableName: dt_storesalesservice_canonical_appointment_v2_avro_prd
  athenaResultBucket: dt-ore-prd
  athenaResultFolder: athena_results_qa/Unsaved
  timeout: 10
